//import { Inter } from "next/font/google";
import 'semantic-ui-css/semantic.min.css'
import "./globals.css";
import StoreProvider from '@/context/StoreProvider';
import quizData from "@/utilities/DataSource";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log(quizData)
  return (
    <html lang="en">
      <body>
        <StoreProvider examData={quizData}>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
